services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-local
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5678:5678"
    environment:
      - TZ=Europe/Moscow
      - GENERIC_TIMEZONE=Europe/Moscow
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
